name: Notificationservice CI

on:
  push:
    paths:
      - 'notificationservice/**'
    branches: [main]
  pull_request:
    paths:
      - 'notificationservice/**'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        working-directory: notificationservice
